//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO.ADO.NET.Control.SOUT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organization()
        {
            this.Departments = new HashSet<Departments>();
        }
    
        public int OrganizationID { get; set; }
        public string Name { get; set; }
        public string NameShort { get; set; }
        public string Adress { get; set; }
        public string AdressFact { get; set; }
        public string DirectorFIO { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public long SOUTid { get; set; }
        public long INN { get; set; }
        public long OKPO { get; set; }
        public long OKOGU { get; set; }
        public string OKVED { get; set; }
        public long OKTMO { get; set; }
        public long OGRN { get; set; }
        public long KPP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departments> Departments { get; set; }
    }
}
